import "./globals.css";
import Footer from "../components/footer/page";
import Navbar from "../components/navbar/page";
import { Roboto } from "next/font/google";
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Tourism Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`max-w-screen-xl mx-auto ${roboto.className}`}>
        <Navbar></Navbar>
        <div className="pt-[78px]">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
